### ISSUE TITLE
./zcoind -reindex-chainstate gets stuck on block 2625

### ISSUE THREAD

**Issue by j3ko** [zcoinofficial/zcoin#194]
OS: Ubuntu 16.04
Version: v0.13.5.7

Steps to reproduce:
1. Run `./zcoind` and sync the blockchain either to completion or partially
2. `./zcoin-cli stop`
3. Run `./zcoind -reindex-chainstate`

Syncing gets stuck at block 2625 everytime no matter how much you have synced previously.  If I delete the entire `.zcoin` directory and directly run `./zcoind -reindex-chainstate` it does not get stuck and continues to completion.

**Comment by devwarrior777** [comment]
Hi .. these issues are resolved in:
- https://github.com/zcoinofficial/zcoin/releases/tag/v0.13.5.8

Also;
 - Use `./zcoind  -reindex` (withiut the the -chainstate)

May we close this issue?

**Comment by j3ko** [comment]
Hi @devwarrior777,

This still seems to be reproducible in v0.13.5.8.

From my understanding `./zcoind -reindex` wipes the block index while `./zcoind -reindex-chainstate` does not.  I am using `./zcoind -reindex` currently,  as it also serves my purpose but as the blockchain gets larger it would be nice to not have to rebuild the block index every time I need to resync.

You may close this issue but I still believe there is a bug here.

**Comment by reubenyap** [comment]
Interesting will look into this thanks

**Comment by reubenyap** [comment]
@FreakyMaryk please verify if this is resolved in latest release and close if it is.

**Comment by FreakyMaryk** [comment]
Hello, everyone!
The bug is still exists on 0.13.7.1, can't close it.
@psolstice Could you please take a look?

**Comment by riordant** [comment]
Appears resolved as of 0.13.7.7. @FreakyMaryk Can you also replicate to make sure
